# Generated by Django 5.1.5 on 2026-01-30 00:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Provider Name')),
                ('code', models.SlugField(help_text="Unique identifier, e.g., 'ecpay'", unique=True, verbose_name='Provider Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('config', models.JSONField(blank=True, default=dict, help_text='API Keys, Merchant IDs, etc.', verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_trade_no', models.CharField(max_length=64, unique=True, verbose_name='Merchant Trade No')),
                ('trade_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='Provider Trade No')),
                ('amount', models.DecimalField(decimal_places=0, help_text='TWD usually has no decimals', max_digits=12, verbose_name='Amount')),
                ('currency', models.CharField(default='TWD', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20, verbose_name='Status')),
                ('object_id', models.PositiveIntegerField()),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='Payment Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Full response from provider', verbose_name='Response Data')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payment.paymentprovider')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
