# Generated by Django 5.1.5 on 2026-01-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='員工編號')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='身份證字號')),
                ('mobile', models.CharField(max_length=20, verbose_name='手機')),
                ('address', models.CharField(max_length=255, verbose_name='通訊地址')),
                ('line_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='LineID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': '員工資料',
                'verbose_name_plural': '員工資料',
                'ordering': ['employee_id'],
            },
        ),
    ]
