# Generated by Django 5.1.5 on 2026-01-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='分機號碼'),
        ),
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.CharField(blank=True, choices=[('A', 'A組'), ('B', 'B組')], max_length=10, null=True, verbose_name='組別'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, choices=[('member', '組員'), ('leader', '組長'), ('accountant', '會計師')], max_length=20, null=True, verbose_name='職稱'),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', '在職'), ('resigned', '離職'), ('leave', '留職停薪')], default='active', max_length=20, verbose_name='狀態'),
        ),
    ]
