# Generated by Django 5.1.5 on 2026-01-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_extension_employee_group_employee_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
    ]
