# Generated by Django 5.1.5 on 2026-01-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=50, unique=True, verbose_name='服務代碼')),
                ('service_name', models.CharField(max_length=100, verbose_name='服務名稱')),
                ('reference_price', models.IntegerField(default=0, verbose_name='參考價格')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='部門')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '收費明細',
                'verbose_name_plural': '收費明細',
                'ordering': ['service_code'],
            },
        ),
    ]
