# Generated by Django 5.1.5 on 2026-01-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='department',
            field=models.CharField(blank=True, choices=[('bookkeeping', '記帳'), ('audit', '查帳'), ('registration', '登記'), ('advance_payment', '代墊')], max_length=20, null=True, verbose_name='部門'),
        ),
    ]
