# Generated by Django 5.1.5 on 2026-01-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_serviceitem_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('tags', models.CharField(help_text='例如：有限公司 跨縣市 變更登記', max_length=200, verbose_name='適用情境')),
                ('checklist', models.TextField(blank=True, null=True, verbose_name='必備文件')),
                ('steps', models.TextField(blank=True, null=True, verbose_name='操作流程')),
                ('warnings', models.TextField(blank=True, null=True, verbose_name='專家注意事項')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '知識筆記',
                'verbose_name_plural': '知識筆記',
                'ordering': ['-created_at'],
            },
        ),
    ]
