# Generated by Django 5.1.5 on 2026-01-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_knowledgenote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='案件類別名稱')),
            ],
            options={
                'verbose_name': '案件類別',
                'verbose_name_plural': '案件類別',
                'ordering': ['name'],
            },
        ),
    ]
