# Generated by Django 5.1.5 on 2026-01-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_casetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='is_aml_required',
            field=models.BooleanField(default=False, verbose_name='需洗錢防制'),
        ),
    ]
