# Generated by Django 5.1.5 on 2026-01-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_serviceitem_is_aml_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, max_length=255, verbose_name='Gemini API Key')),
                ('line_access_token', models.CharField(blank=True, max_length=255, verbose_name='Line Access Token')),
                ('line_web_url', models.URLField(blank=True, verbose_name='Line Web Hook')),
                ('ecpay_merchant_id', models.CharField(blank=True, max_length=50, verbose_name='綠界 Merchant ID')),
                ('ecpay_hash_key', models.CharField(blank=True, max_length=50, verbose_name='綠界 Hash Key')),
                ('ecpay_hash_iv', models.CharField(blank=True, max_length=50, verbose_name='綠界 Hash IV')),
            ],
            options={
                'verbose_name': '系統參數',
                'verbose_name_plural': '系統參數',
            },
        ),
    ]
