# Generated by Django 5.1.5 on 2026-01-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.CharField(help_text='請輸入8位數公司統一編號', max_length=8, unique=True, verbose_name='公司統編')),
                ('companyName', models.CharField(max_length=200, verbose_name='公司名稱')),
                ('contact', models.CharField(max_length=100, verbose_name='聯絡人')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='電子郵件')),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='公司電話')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡人手機')),
                ('LineId', models.CharField(blank=True, max_length=50, null=True, verbose_name='Line ID')),
                ('registration_address', models.TextField(verbose_name='登記地址')),
                ('mailing_address', models.TextField(blank=True, help_text='若未填寫，則與登記地址相同', null=True, verbose_name='通訊地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '客戶基本資料',
                'verbose_name_plural': '客戶基本資料',
                'db_table': 'basic_information',
                'ordering': ['-created_at'],
            },
        ),
    ]
