# Generated by Django 5.1.5 on 2026-01-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='account_last_5',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='帳號後五碼'),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='fax_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='傳真號碼'),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='important_notes',
            field=models.TextField(blank=True, null=True, verbose_name='重要訊息描述'),
        ),
    ]
