# Generated by Django 5.1.5 on 2026-01-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_basicinformation_account_last_5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名稱')),
                ('company_id', models.CharField(help_text='請輸入8位數統一編號', max_length=8, verbose_name='統一編號')),
                ('name', models.CharField(max_length=100, verbose_name='聯絡人姓名')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='職稱')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手機')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='傳真')),
                ('address', models.TextField(blank=True, null=True, verbose_name='通訊地址')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '聯絡人',
                'verbose_name_plural': '聯絡人',
                'db_table': 'contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
