# Generated by Django 5.1.5 on 2026-01-11 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('serial_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='序號')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '收文主記錄',
                'verbose_name_plural': '收文主記錄',
                'db_table': 'incoming_mail',
                'ordering': ['-date', '-serial_number'],
            },
        ),
        migrations.CreateModel(
            name='IncomingMailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200, verbose_name='寄件人')),
                ('customer_name', models.CharField(max_length=200, verbose_name='歸屬客戶')),
                ('content_type', models.CharField(choices=[('accounting_voucher', '會計/營業憑證'), ('nta_chinese', '國稅局中文')], max_length=50, verbose_name='內容')),
                ('notify_customer', models.BooleanField(default=False, verbose_name='通知客戶')),
                ('message_content', models.TextField(blank=True, null=True, verbose_name='傳送訊息內容')),
                ('order', models.IntegerField(default=0, verbose_name='排序順序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('company', models.ForeignKey(help_text='請從客戶基本資料中選取', on_delete=django.db.models.deletion.PROTECT, to='admin_module.basicinformation', verbose_name='統一編號')),
                ('incoming_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='admin_module.incomingmail', verbose_name='收文主記錄')),
            ],
            options={
                'verbose_name': '收文明細記錄',
                'verbose_name_plural': '收文明細記錄',
                'db_table': 'incoming_mail_item',
                'ordering': ['incoming_mail', 'order'],
            },
        ),
    ]
