# Generated by Django 5.1.5 on 2026-01-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0004_incomingmail_incomingmailitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(help_text='請輸入8位數統一編號', max_length=8, verbose_name='統一編號')),
                ('company_name', models.CharField(max_length=200, verbose_name='客戶名稱')),
                ('accounting_assistant', models.CharField(max_length=100, verbose_name='記帳助理人員')),
                ('overdue_days', models.IntegerField(default=0, verbose_name='逾期天數')),
                ('establishment_date', models.DateField(verbose_name='立案日期')),
                ('change_type', models.CharField(choices=[('new_establishment', '新設立'), ('transfer_in', '轉入'), ('transfer_out', '轉出'), ('dissolution', '解散')], max_length=20, verbose_name='種類')),
                ('invoice_quantity', models.BooleanField(default=False, verbose_name='發票本數')),
                ('id_copy', models.BooleanField(default=False, verbose_name='負責人身分證影本')),
                ('lease_and_tax', models.BooleanField(default=False, verbose_name='租約及稅單')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '客戶增減',
                'verbose_name_plural': '客戶增減',
                'db_table': 'customer_change',
                'ordering': ['-created_at'],
            },
        ),
    ]
