# Generated by Django 5.1.5 on 2026-01-12 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0005_customerchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('check_period', models.CharField(help_text='例如：113年1-2月', max_length=50, verbose_name='檢查期間')),
                ('inspector', models.CharField(max_length=100, verbose_name='檢查人員')),
                ('inspectee', models.CharField(max_length=100, verbose_name='受檢人員')),
                ('status', models.CharField(choices=[('pending', '尚未完成'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='完成狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '營業稅檢查',
                'verbose_name_plural': '營業稅檢查',
                'db_table': 'vat_check',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VATCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(help_text='請輸入8位數統一編號', max_length=8, verbose_name='統一編號')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名稱')),
                ('input_buyer', models.CharField(blank=True, max_length=200, null=True, verbose_name='進項買受人')),
                ('check_input_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='進項金額（檢查）')),
                ('input_duplicate', models.CharField(blank=True, max_length=100, null=True, verbose_name='進項重複')),
                ('output_e_invoice', models.CharField(blank=True, max_length=100, null=True, verbose_name='銷項電子發票')),
                ('form401_output_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='銷項金額（401）')),
                ('form401_input_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='進項金額（401）')),
                ('tax_credit_carried_forward', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='留抵稅額')),
                ('tax_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='應納稅額')),
                ('tax_refundable', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='應退稅額')),
                ('order', models.IntegerField(default=0, verbose_name='排序順序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('vat_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='admin_module.vatcheck', verbose_name='營業稅檢查主記錄')),
            ],
            options={
                'verbose_name': '營業稅檢查明細',
                'verbose_name_plural': '營業稅檢查明細',
                'db_table': 'vat_check_item',
                'ordering': ['vat_check', 'order'],
            },
        ),
    ]
