# Generated by Django 5.1.5 on 2026-01-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0006_vatcheck_vatcheckitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeepingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.CharField(max_length=50, verbose_name='序號')),
                ('check_period', models.CharField(max_length=50, verbose_name='檢查期別')),
                ('company_id', models.CharField(max_length=8, verbose_name='統一編號')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名稱')),
                ('bookkeeper', models.CharField(max_length=100, verbose_name='記帳助理人員')),
                ('industry_code', models.CharField(max_length=20, verbose_name='行業別代號')),
                ('industry_name', models.CharField(max_length=200, verbose_name='行業別名稱')),
                ('status', models.CharField(choices=[('not_started', '尚未開始'), ('completed', '已完成')], default='not_started', max_length=20, verbose_name='狀態')),
                ('revenue_listed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='收入帳列數')),
                ('revenue_reported', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='收入申報數')),
                ('cost_listed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='成本帳列數')),
                ('cost_reported', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='成本申報數')),
                ('gross_profit_listed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='毛利帳列數')),
                ('gross_profit_reported', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='毛利申報數')),
                ('operating_expense_listed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='營業費用帳列數')),
                ('operating_expense_reported', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='營業費用申報數')),
                ('operating_profit_listed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='營業利益帳列數')),
                ('operating_profit_reported', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='營業利益申報數')),
                ('non_operating_income_listed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='業外收入帳列數')),
                ('non_operating_income_reported', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='業外收入申報數')),
                ('non_operating_expense_listed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='業外支出帳列數')),
                ('non_operating_expense_reported', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='業外支出申報數')),
                ('net_profit_listed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='淨利帳列數')),
                ('net_profit_reported', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='淨利申報數')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='結論')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '記帳進度檢查',
                'verbose_name_plural': '記帳進度檢查',
                'db_table': 'bookkeeping_checklist',
                'ordering': ['-created_at'],
            },
        ),
    ]
