# Generated by Django 5.1.5 on 2026-01-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0007_bookkeepingchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeepingchecklist',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已刪除'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已刪除'),
        ),
        migrations.AddField(
            model_name='customerchange',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已刪除'),
        ),
        migrations.AddField(
            model_name='incomingmail',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已刪除'),
        ),
        migrations.AddField(
            model_name='vatcheck',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已刪除'),
        ),
    ]
