# Generated by Django 5.1.5 on 2026-01-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0008_bookkeepingchecklist_is_deleted_contact_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已刪除'),
        ),
    ]
