# Generated by Django 5.1.5 on 2026-01-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0009_basicinformation_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='mailing_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='通訊地址郵遞區號'),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='registration_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='登記地址郵遞區號'),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='room_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Room ID'),
        ),
    ]
