# Generated by Django 5.1.5 on 2026-01-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名稱')),
                ('company_id', models.CharField(help_text='請輸入8位數統一編號', max_length=8, unique=True, verbose_name='統一編號')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='稅籍編號')),
                ('registration_address', models.TextField(verbose_name='登記地址')),
                ('mailing_address', models.TextField(blank=True, null=True, verbose_name='通訊地址')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contact_person', models.CharField(max_length=100, verbose_name='聯絡人')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話')),
                ('line_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Line ID')),
                ('business_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='營業人密碼')),
                ('charge_status', models.CharField(choices=[('charging', '收費中'), ('not_charging', '未收費')], default='charging', max_length=20, verbose_name='收費狀態')),
                ('charge_method', models.CharField(choices=[('annual', '年繳'), ('prepaid', '預繳'), ('monthly', '月繳'), ('auto_debit', '自動扣繳'), ('semi_annual', '半年繳')], default='annual', max_length=20, verbose_name='收費方式')),
                ('undertaking_status', models.CharField(choices=[('undertaking', '承接中'), ('suspended', '停業'), ('transferred_out', '轉出'), ('dissolved', '解散'), ('pending_transfer_out', '待轉出'), ('pending_transfer_in', '待轉入')], default='undertaking', max_length=30, verbose_name='承接狀態')),
                ('industry_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='行業代碼')),
                ('industry_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='行業名稱')),
                ('business_type', models.CharField(choices=[('exclusive', '專營營業人'), ('concurrent_direct', '兼營(直扣)'), ('concurrent_proportion', '兼營(比例)'), ('professional_investment', '專業投資'), ('non_business', '非營業人')], default='exclusive', max_length=30, verbose_name='營業人類型')),
                ('e_invoice_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='電子發票帳號')),
                ('e_invoice_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='電子發票密碼')),
                ('invoice_purchase_method', models.CharField(choices=[('unified_purchase', '統購'), ('customer_purchase', '客戶自己買'), ('no_purchase', '沒買')], default='unified_purchase', max_length=30, verbose_name='買發票方式')),
                ('invoice_delivery_method', models.CharField(choices=[('mail', '郵寄'), ('office_keep', '事務所保留'), ('no_purchase', '沒買')], default='mail', max_length=30, verbose_name='送發票方式')),
                ('invoice_receive_method', models.CharField(choices=[('seven_eleven', '7-11便利待'), ('self_collect', '親收'), ('customer_send', '客戶送來')], default='seven_eleven', max_length=30, verbose_name='收發票方式')),
                ('tax_payment', models.CharField(blank=True, choices=[('self_pay', '自繳'), ('agent_pay', '代繳'), ('not_replied', '尚未回覆'), ('auto_debit', '自動扣款')], max_length=20, null=True, verbose_name='繳稅')),
                ('notification_method', models.CharField(blank=True, choices=[('email', 'Email'), ('line', 'Line'), ('both', 'Both')], max_length=20, null=True, verbose_name='通知方式')),
                ('important_notes', models.TextField(blank=True, null=True, verbose_name='重要備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '記帳客戶',
                'verbose_name_plural': '記帳客戶',
                'db_table': 'booking_customer',
                'ordering': ['-created_at'],
            },
        ),
    ]
