# Generated by Django 5.1.5 on 2026-01-14 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxAuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='從客戶資料自動帶入', max_length=200, verbose_name='公司名稱')),
                ('email', models.EmailField(blank=True, help_text='從客戶資料自動帶入', max_length=254, null=True, verbose_name='Email')),
                ('year', models.CharField(max_length=4, verbose_name='年度')),
                ('tax_type', models.CharField(choices=[('vat', '營業稅'), ('income', '所得稅'), ('stamp', '印花稅'), ('personal_income', '個人綜所'), ('other', '其他')], max_length=20, verbose_name='稅種')),
                ('reason', models.CharField(choices=[('audit', '查帳'), ('correction', '更正')], max_length=20, verbose_name='原因')),
                ('letter_date', models.DateField(blank=True, null=True, verbose_name='來函日期')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='送件日期')),
                ('progress', models.CharField(choices=[('discussing', '討論中'), ('closed', '結案')], default='discussing', max_length=20, verbose_name='進度')),
                ('jurisdiction', models.CharField(blank=True, max_length=100, null=True, verbose_name='轄區')),
                ('jurisdiction_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='轄區電話')),
                ('handler', models.CharField(blank=True, max_length=100, null=True, verbose_name='承辦人')),
                ('handler_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='承辦人電話')),
                ('handler_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='承辦人Email')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='傳真')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tax_audit_records/%Y/%m/', verbose_name='上傳檔案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('customer', models.ForeignKey(help_text='選擇客戶以自動帶入公司名稱和Email', on_delete=django.db.models.deletion.PROTECT, to='booking.bookingcustomer', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '國稅局查帳紀錄',
                'verbose_name_plural': '國稅局查帳紀錄',
                'db_table': 'tax_audit_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxAuditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateField(verbose_name='聯絡日期')),
                ('discussion_content', models.TextField(verbose_name='討論內容')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tax_audit_histories/%Y/%m/', verbose_name='上傳附件')),
                ('order', models.IntegerField(default=0, verbose_name='排序順序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('audit_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='booking.taxauditrecord', verbose_name='查帳紀錄')),
            ],
            options={
                'verbose_name': '查帳歷程',
                'verbose_name_plural': '查帳歷程',
                'db_table': 'tax_audit_history',
                'ordering': ['audit_record', 'contact_date', 'order'],
            },
        ),
    ]
