# Generated by Django 5.1.5 on 2026-01-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_taxauditrecord_taxaudithistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxauditrecord',
            name='submission_date',
        ),
        migrations.AddField(
            model_name='taxauditrecord',
            name='expected_reply_date',
            field=models.DateField(blank=True, null=True, verbose_name='預計回覆日期'),
        ),
        migrations.AlterField(
            model_name='taxauditrecord',
            name='letter_date',
            field=models.DateField(blank=True, null=True, verbose_name='來函/送件日期'),
        ),
    ]
