# Generated by Django 5.1.5 on 2026-01-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_taxauditrecord_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcustomer',
            name='assistant_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='請輸入0-100之間的數字', max_digits=5, null=True, verbose_name='助理比例'),
        ),
        migrations.AddField(
            model_name='bookingcustomer',
            name='bookkeeping_assistant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='記帳助理'),
        ),
        migrations.AddField(
            model_name='bookingcustomer',
            name='business_registration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='工商'),
        ),
        migrations.AddField(
            model_name='bookingcustomer',
            name='business_registration_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='請輸入0-100之間的數字', max_digits=5, null=True, verbose_name='工商比例'),
        ),
        migrations.AddField(
            model_name='bookingcustomer',
            name='contact_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='請輸入0-100之間的數字', max_digits=5, null=True, verbose_name='窗口比例'),
        ),
        migrations.AddField(
            model_name='bookingcustomer',
            name='group_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='集團窗口'),
        ),
        migrations.AddField(
            model_name='bookingcustomer',
            name='invoice_qty_2_cashier',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='二收銀'),
        ),
        migrations.AddField(
            model_name='bookingcustomer',
            name='invoice_qty_2_copy',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='二聯'),
        ),
        migrations.AddField(
            model_name='bookingcustomer',
            name='invoice_qty_2_副copy',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='二聯副'),
        ),
        migrations.AddField(
            model_name='bookingcustomer',
            name='invoice_qty_3_cashier',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='三收銀'),
        ),
        migrations.AddField(
            model_name='bookingcustomer',
            name='invoice_qty_3_cashier_副',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='三收銀副'),
        ),
        migrations.AddField(
            model_name='bookingcustomer',
            name='invoice_qty_3_copy',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='三聯'),
        ),
        migrations.AddField(
            model_name='bookingcustomer',
            name='invoice_qty_3_副copy',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='三聯副'),
        ),
        migrations.AddField(
            model_name='bookingcustomer',
            name='invoice_qty_special',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='特種'),
        ),
        migrations.AddField(
            model_name='bookingcustomer',
            name='reviewer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='review人員'),
        ),
        migrations.AddField(
            model_name='bookingcustomer',
            name='reviewer_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='請輸入0-100之間的數字', max_digits=5, null=True, verbose_name='review比例'),
        ),
    ]
