# Generated by Django 5.1.5 on 2026-01-16 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookingcustomer_assistant_ratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_year', models.CharField(help_text='例如: 113', max_length=4, verbose_name='申報年度')),
                ('filing_period', models.CharField(choices=[('01', '1月'), ('03', '3月'), ('05', '5月'), ('07', '7月'), ('09', '9月'), ('11', '11月')], max_length=2, verbose_name='申報期別')),
                ('tax_payable', models.BooleanField(default=False, verbose_name='是否繳稅')),
                ('tax_deadline', models.DateField(blank=True, null=True, verbose_name='繳稅截止日')),
                ('invoice_received_date', models.DateField(blank=True, null=True, verbose_name='收到發票日期')),
                ('tax_payment_completed', models.BooleanField(default=False, verbose_name='繳稅完成否')),
                ('source', models.CharField(blank=True, choices=[('customer_provided', '客戶提供'), ('office_assisted', '事務所協助'), ('accountant_collected', '會計師收集'), ('electronic_download', '電子下載')], max_length=30, null=True, verbose_name='來源')),
                ('reply_time', models.DateTimeField(blank=True, null=True, verbose_name='回覆時間')),
                ('declaration_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='申報書網址')),
                ('payment_slip_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='繳款書網址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('customer', models.ForeignKey(help_text='選擇客戶以自動帶入基本資料', on_delete=django.db.models.deletion.PROTECT, to='booking.bookingcustomer', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '營業稅申報記錄',
                'verbose_name_plural': '營業稅申報記錄',
                'db_table': 'vat_record',
                'ordering': ['-filing_year', '-filing_period', '-created_at'],
                'unique_together': {('customer', 'filing_year', 'filing_period')},
            },
        ),
    ]
