# Generated by Django 5.1.5 on 2026-01-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_vatrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatrecord',
            name='credit_carryforward',
            field=models.IntegerField(blank=True, help_text='輸入整數金額', null=True, verbose_name='留底抵稅額'),
        ),
        migrations.AddField(
            model_name='vatrecord',
            name='purchase_amount',
            field=models.IntegerField(blank=True, help_text='輸入整數金額', null=True, verbose_name='進項金額'),
        ),
        migrations.AddField(
            model_name='vatrecord',
            name='sales_amount',
            field=models.IntegerField(blank=True, help_text='輸入整數金額', null=True, verbose_name='銷項金額'),
        ),
        migrations.AddField(
            model_name='vatrecord',
            name='tax_payable_amount',
            field=models.IntegerField(blank=True, help_text='輸入整數金額', null=True, verbose_name='應納稅額'),
        ),
        migrations.AddField(
            model_name='vatrecord',
            name='tax_refund_amount',
            field=models.IntegerField(blank=True, help_text='輸入整數金額', null=True, verbose_name='應退稅額'),
        ),
        migrations.AlterField(
            model_name='vatrecord',
            name='tax_payable',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True, verbose_name='是否繳稅'),
        ),
        migrations.AlterField(
            model_name='vatrecord',
            name='tax_payment_completed',
            field=models.CharField(blank=True, choices=[('customer_paid', '客戶自己繳納'), ('office_paid', '事務所代繳'), ('not_replied', '還沒回覆')], max_length=20, null=True, verbose_name='繳稅完成否'),
        ),
    ]
