# Generated by Django 5.1.5 on 2026-01-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_vatrecord_credit_carryforward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatrecord',
            name='completion_status',
            field=models.CharField(blank=True, choices=[('completed', '已完成'), ('not_started', '尚未開始')], max_length=20, null=True, verbose_name='完成狀態'),
        ),
    ]
