# Generated by Django 5.1.5 on 2026-01-17 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_vatrecord_completion_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_year', models.IntegerField(help_text='例如：113', verbose_name='申報年度')),
                ('important_notes', models.TextField(blank=True, help_text='顯示在表單頂部的重要提醒', null=True, verbose_name='重要提醒事項')),
                ('provisional_payment', models.IntegerField(blank=True, default=0, help_text='輸入整數金額，此金額會自動填入本稅區塊的暫繳-62欄', null=True, verbose_name='暫繳金額')),
                ('dividend_distribution', models.IntegerField(blank=True, default=0, help_text='輸入整數金額', null=True, verbose_name='股利分配金額')),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='收件編號')),
                ('filing_type', models.CharField(blank=True, choices=[('book_review', '書審'), ('income_standard', '所標'), ('account_audit', '查帳'), ('accounting_sign', '會簽'), ('other', '其他')], max_length=20, null=True, verbose_name='申報類別')),
                ('tax_payable_col60', models.IntegerField(blank=True, default=0, help_text='輸入整數金額', null=True, verbose_name='應納稅額(60欄)')),
                ('provisional_col62', models.IntegerField(blank=True, default=0, help_text='自動從暫繳金額填入，唯讀', null=True, verbose_name='暫繳(62欄)')),
                ('withholding_col63', models.IntegerField(blank=True, default=0, help_text='輸入整數金額', null=True, verbose_name='扣繳(63欄)')),
                ('land_building_col65', models.IntegerField(blank=True, default=0, help_text='輸入整數金額', null=True, verbose_name='房地合一(65欄)')),
                ('other_amount', models.IntegerField(blank=True, default=0, help_text='輸入整數金額', null=True, verbose_name='其他')),
                ('refund_or_payment', models.IntegerField(blank=True, default=0, help_text='自動計算：應納稅額 - 暫繳 - 扣繳 + 房地合一 - 其他', null=True, verbose_name='補繳金額(64)應退(65)')),
                ('unallocated_surtax', models.IntegerField(blank=True, default=0, help_text='輸入整數金額', null=True, verbose_name='未分加徵稅額')),
                ('final_refund_or_payment', models.IntegerField(blank=True, default=0, help_text='自動計算', null=True, verbose_name='抵完後應補(退)')),
                ('total_tax', models.IntegerField(blank=True, default=0, help_text='自動計算', null=True, verbose_name='總計稅款')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_tax_records', to='booking.bookingcustomer', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '所得稅申報記錄',
                'verbose_name_plural': '所得稅申報記錄',
                'db_table': 'income_tax_record',
                'ordering': ['-filing_year', '-created_at'],
                'unique_together': {('customer', 'filing_year')},
            },
        ),
    ]
