# Generated by Django 5.1.5 on 2026-01-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_incometaxrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometaxrecord',
            name='declaration_url',
            field=models.URLField(blank=True, help_text='輸入申報書的完整網址', max_length=500, null=True, verbose_name='申報書網址'),
        ),
        migrations.AddField(
            model_name='incometaxrecord',
            name='payment_slip_url',
            field=models.URLField(blank=True, help_text='輸入繳款書的完整網址', max_length=500, null=True, verbose_name='繳款書網址'),
        ),
    ]
