# Generated by Django 5.1.5 on 2026-01-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_incometaxrecord_declaration_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometaxrecord',
            name='bad_debt_expense',
            field=models.CharField(blank=True, choices=[('confirmed', '確認未超限')], max_length=20, null=True, verbose_name='壞帳費用'),
        ),
        migrations.AddField(
            model_name='incometaxrecord',
            name='cost_statement',
            field=models.CharField(blank=True, choices=[('matched', '成本表相符'), ('not_prepared', '無編制成本表')], max_length=20, null=True, verbose_name='成本表'),
        ),
        migrations.AddField(
            model_name='incometaxrecord',
            name='employee_welfare',
            field=models.CharField(blank=True, choices=[('confirmed', '確認未超限')], max_length=20, null=True, verbose_name='職工福利'),
        ),
        migrations.AddField(
            model_name='incometaxrecord',
            name='entertainment_expense',
            field=models.CharField(blank=True, choices=[('confirmed', '確認未超限')], max_length=20, null=True, verbose_name='交際費'),
        ),
        migrations.AddField(
            model_name='incometaxrecord',
            name='income_401_reconciliation',
            field=models.CharField(blank=True, choices=[('reconciled', '調節相符申報'), ('zero', '申報0'), ('not_applicable', '無此情形')], max_length=20, null=True, verbose_name='收入與401調節相符'),
        ),
        migrations.AddField(
            model_name='incometaxrecord',
            name='income_expense_match',
            field=models.CharField(blank=True, choices=[('confirmed', '確認無誤'), ('no_tax_expense', '無所得稅費用')], max_length=20, null=True, verbose_name='所得費用相符'),
        ),
        migrations.AddField(
            model_name='incometaxrecord',
            name='land_transaction',
            field=models.CharField(blank=True, choices=[('c4_filled', 'C4表已填'), ('no_transaction', '無土地交易')], max_length=20, null=True, verbose_name='土地交易'),
        ),
        migrations.AddField(
            model_name='incometaxrecord',
            name='provisional_withholding_deduction',
            field=models.CharField(blank=True, choices=[('deducted', '已扣除'), ('not_applicable', '無暫繳或扣繳')], max_length=20, null=True, verbose_name='暫繳及扣繳要扣除'),
        ),
        migrations.AddField(
            model_name='incometaxrecord',
            name='undistributed_earnings_surtax',
            field=models.CharField(blank=True, choices=[('no_earnings', '沒有未分配盈餘'), ('surtax_correct', '加徵稅額計算無誤')], max_length=20, null=True, verbose_name='未分配盈餘加徵'),
        ),
    ]
