# Generated by Django 5.1.5 on 2026-01-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_incometaxrecord_bad_debt_expense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(help_text='資料檔案編號', max_length=50, verbose_name='檔案編號')),
                ('year', models.IntegerField(help_text='申報年度', verbose_name='年度')),
                ('period', models.CharField(help_text='申報期別', max_length=20, verbose_name='期別')),
                ('category', models.CharField(help_text='資料種類', max_length=50, verbose_name='種類')),
                ('company_id', models.CharField(help_text='公司統一編號', max_length=8, verbose_name='統一編號')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名稱')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('invoice_received_date', models.DateField(blank=True, null=True, verbose_name='收到發票日期')),
                ('payment_method', models.CharField(blank=True, choices=[('customer', '客戶自己繳'), ('office', '事務所代繳'), ('no_reply', '還沒回覆')], max_length=20, null=True, verbose_name='繳稅方式')),
                ('source', models.CharField(blank=True, choices=[('google', 'Google'), ('manual', '自行輸入'), ('na', 'NA')], max_length=20, null=True, verbose_name='來源')),
                ('reply_time', models.DateTimeField(blank=True, null=True, verbose_name='回覆時間')),
                ('declaration_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='申報書網址')),
                ('payment_slip_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='繳款書網址')),
                ('tax_deadline', models.DateField(blank=True, null=True, verbose_name='繳稅截止日')),
                ('status', models.CharField(choices=[('current', '當期'), ('previous', '上期')], default='current', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '下載資料',
                'verbose_name_plural': '下載資料',
                'db_table': 'download_data',
                'ordering': ['-year', '-period', '-created_at'],
            },
        ),
    ]
