# Generated by Django 5.1.5 on 2026-01-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_downloaddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaddata',
            name='category',
            field=models.CharField(blank=True, choices=[('vat', '營業稅'), ('income_tax', '所得稅'), ('provisional', '暫繳')], help_text='資料種類', max_length=50, null=True, verbose_name='種類'),
        ),
    ]
