# Generated by Django 5.1.5 on 2026-01-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_downloaddata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatrecord',
            name='filing_period',
            field=models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, verbose_name='申報期別'),
        ),
        migrations.AlterField(
            model_name='vatrecord',
            name='source',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('manual', '自行輸入'), ('na', 'NA')], max_length=30, null=True, verbose_name='來源'),
        ),
    ]
