# Generated by Django 5.1.5 on 2026-01-18 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_module', '0007_bookkeepingchecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='個人股東填身分證字號，法人股東填統一編號', max_length=20, unique=True, verbose_name='身分證字號/統一編號')),
                ('name', models.CharField(max_length=100, verbose_name='股東姓名')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡電話')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='電子郵件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '股東',
                'verbose_name_plural': '股東',
                'db_table': 'shareholder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyShareholding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholdings', to='admin_module.basicinformation', verbose_name='公司')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_holdings', to='registration.shareholder', verbose_name='股東')),
            ],
            options={
                'verbose_name': '持股關係',
                'verbose_name_plural': '持股關係',
                'db_table': 'company_shareholding',
                'ordering': ['company', 'shareholder'],
                'unique_together': {('shareholder', 'company')},
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='交易日期')),
                ('transaction_type', models.CharField(choices=[('founding', '原始設立'), ('transfer_in', '轉入'), ('transfer_out', '轉出'), ('capital_increase', '增資'), ('capital_reduction', '減資')], max_length=20, verbose_name='交易類型')),
                ('quantity', models.IntegerField(help_text='轉入/增資為正數，轉出/減資為負數', verbose_name='股數')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='交易金額（票面價值或交易價格）', max_digits=15, null=True, verbose_name='金額')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('company_holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='registration.companyshareholding', verbose_name='持股關係')),
            ],
            options={
                'verbose_name': '股權交易記錄',
                'verbose_name_plural': '股權交易記錄',
                'db_table': 'stock_transaction',
                'ordering': ['transaction_date', 'created_at'],
            },
        ),
    ]
