# Generated by Django 5.1.5 on 2026-01-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='交易說明'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='par_value',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='每股面額'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='stock_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='每股面額 × 股數', max_digits=15, verbose_name='股票金額'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='stock_type',
            field=models.CharField(choices=[('common', '普通股'), ('preferred', '特別股')], default='common', max_length=20, verbose_name='股票類型'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='實際交易價格（可能不等於股票金額）', max_digits=15, null=True, verbose_name='交易金額'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='備註'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.IntegerField(verbose_name='股數'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('founding', '設立'), ('capital_reduction', '減資'), ('trade', '買賣'), ('gift', '贈與'), ('transfer_in', '轉入'), ('transfer_out', '轉出')], max_length=20, verbose_name='交易類型'),
        ),
    ]
