# Generated by Django 5.1.5 on 2026-01-21 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0007_bookkeepingchecklist'),
        ('registration', '0002_stocktransaction_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('chairman', '董事長'), ('director', '董事'), ('supervisor', '監察人')], max_length=20, verbose_name='職稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_members', to='admin_module.basicinformation', verbose_name='公司')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_positions', to='registration.shareholder', verbose_name='姓名')),
                ('representative_of', models.ForeignKey(blank=True, help_text='若此人為法人代表，請選擇所代表之法人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represented_by', to='registration.shareholder', verbose_name='所代表法人')),
            ],
            options={
                'verbose_name': '董監事',
                'verbose_name_plural': '董監事',
                'db_table': 'board_member',
                'ordering': ['company', 'title', 'person'],
            },
        ),
    ]
