# Generated by Django 5.1.5 on 2026-01-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_boardmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
    ]
