# Generated by Django 5.1.5 on 2026-01-22 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_boardmember_birthday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AddField(
            model_name='companyshareholding',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),
        migrations.AddField(
            model_name='companyshareholding',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AddField(
            model_name='companyshareholding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否刪除'),
        ),
    ]
