# Generated by Django 5.1.5 on 2026-01-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_boardmember_created_by_boardmember_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholder',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
    ]
