# Generated by Django 5.1.5 on 2026-01-24 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_shareholder_birthday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='案號')),
                ('company_name', models.CharField(max_length=100, verbose_name='公司名稱')),
                ('case_type', models.CharField(max_length=50, verbose_name='案件類型')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('review', '審核中'), ('approved', '已核准'), ('rejected', '已駁回'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='狀態')),
                ('assignee', models.CharField(blank=True, max_length=50, null=True, verbose_name='承辦人')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='收件日期')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='預計完成日')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '登記案件',
                'verbose_name_plural': '登記案件',
                'db_table': 'registration_progress',
                'ordering': ['-created_at'],
            },
        ),
    ]
