# Generated by Django 5.1.5 on 2026-01-24 13:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0009_basicinformation_is_deleted'),
        ('master', '0002_alter_serviceitem_department'),
        ('registration', '0007_registrationprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationprogress',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='registrationprogress',
            name='case_type',
        ),
        migrations.RemoveField(
            model_name='registrationprogress',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='registrationprogress',
            name='start_date',
        ),
        migrations.AddField(
            model_name='registrationprogress',
            name='acceptance_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='承接日期'),
        ),
        migrations.AddField(
            model_name='registrationprogress',
            name='contact_address',
            field=models.TextField(blank=True, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='registrationprogress',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='registrationprogress',
            name='contact_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手機'),
        ),
        migrations.AddField(
            model_name='registrationprogress',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話'),
        ),
        migrations.AddField(
            model_name='registrationprogress',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_cases', to='admin_module.basicinformation', verbose_name='公司名稱'),
        ),
        migrations.AddField(
            model_name='registrationprogress',
            name='delivery_method',
            field=models.CharField(choices=[('self_pickup', '自取'), ('mail', '郵寄')], default='self_pickup', max_length=20, verbose_name='寄送方式'),
        ),
        migrations.AddField(
            model_name='registrationprogress',
            name='main_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_cases', to='admin_module.contact', verbose_name='主要聯絡人'),
        ),
        migrations.AddField(
            model_name='registrationprogress',
            name='mandate_status',
            field=models.CharField(choices=[('not_issued', '未發出'), ('pending_return', '待簽回'), ('approved', '已核准'), ('disagreed', '不同意')], default='not_issued', max_length=20, verbose_name='委任書狀態'),
        ),
        migrations.AddField(
            model_name='registrationprogress',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號'),
        ),
        migrations.AlterField(
            model_name='registrationprogress',
            name='case_number',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='登記案件文號'),
        ),
        migrations.AlterField(
            model_name='registrationprogress',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='預計完成日期'),
        ),
        migrations.AlterField(
            model_name='registrationprogress',
            name='status',
            field=models.CharField(choices=[('discussion', '討論中'), ('new_case', '新接案'), ('documentation', '製作文件中'), ('government_review', '主管機關審查中'), ('closed', '結案'), ('none', '沒有辦理')], default='discussion', max_length=20, verbose_name='案件狀態'),
        ),
        migrations.CreateModel(
            name='RegistrationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('service_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='服務名稱')),
                ('service_item', models.CharField(blank=True, max_length=200, null=True, verbose_name='服務項目')),
                ('fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='服務費用')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='registration.registrationprogress', verbose_name='登記案件')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.serviceitem', verbose_name='服務代碼')),
            ],
            options={
                'verbose_name': '登記案件服務明細',
                'verbose_name_plural': '登記案件服務明細',
                'db_table': 'registration_service',
                'ordering': ['created_at'],
            },
        ),
    ]
