# Generated by Django 5.1.5 on 2026-01-25 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_is_deleted'),
        ('registration', '0008_remove_registrationprogress_assignee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationprogress',
            name='delivery_method',
            field=models.CharField(choices=[('self_pickup', '自取'), ('mail', '郵寄')], default='mail', max_length=20, verbose_name='寄送方式'),
        ),
        migrations.CreateModel(
            name='RegistrationCostSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('ratio', models.DecimalField(decimal_places=2, default=0, help_text='百分比 (Ex: 50.00)', max_digits=5, verbose_name='比例')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='分攤公費')),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee', verbose_name='助理')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_splits', to='registration.registrationprogress', verbose_name='登記案件')),
            ],
            options={
                'verbose_name': '公費拆分',
                'verbose_name_plural': '公費拆分',
                'db_table': 'registration_cost_split',
                'ordering': ['created_at'],
            },
        ),
    ]
