# Generated by Django 5.1.5 on 2026-01-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_casetype'),
        ('registration', '0009_alter_registrationprogress_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationprogress',
            name='case_type',
            field=models.ManyToManyField(blank=True, to='master.casetype', verbose_name='案件類別'),
        ),
    ]
