# Generated by Django 5.1.5 on 2026-01-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_registrationprogress_case_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationprogress',
            name='line_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Line ID'),
        ),
        migrations.AddField(
            model_name='registrationprogress',
            name='room_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Room ID'),
        ),
    ]
