# Generated by Django 5.1.5 on 2026-01-28 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_registrationprogress_line_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationprogress',
            name='status',
            field=models.CharField(choices=[('discussion', '0.討論中'), ('new_case', '1.新接案'), ('documentation', '2.製作中'), ('government_review', '3.審查中'), ('closed', '4.結案'), ('none', '5.沒有辦理')], default='discussion', max_length=20, verbose_name='案件狀態'),
        ),
        migrations.CreateModel(
            name='RegistrationAML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('risk_level', models.CharField(choices=[('low', '低風險'), ('medium', '中風險'), ('high', '高風險')], default='low', max_length=20, verbose_name='風險等級')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='審查紀錄')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aml_record', to='registration.registrationprogress', verbose_name='登記案件')),
            ],
            options={
                'verbose_name': '洗錢防制',
                'verbose_name_plural': '洗錢防制',
                'db_table': 'registration_aml',
            },
        ),
        migrations.CreateModel(
            name='RegistrationMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('mandate_date', models.DateField(blank=True, null=True, verbose_name='委任日期')),
                ('is_signed', models.BooleanField(default=False, verbose_name='是否已簽署')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mandate', to='registration.registrationprogress', verbose_name='登記案件')),
            ],
            options={
                'verbose_name': '委任書',
                'verbose_name_plural': '委任書',
                'db_table': 'registration_mandate',
            },
        ),
    ]
