# Generated by Django 5.1.5 on 2026-01-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_registrationprogress_status_registrationaml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmandate',
            name='is_drafting_agreed',
            field=models.BooleanField(default=False, verbose_name='擬稿同意'),
        ),
        migrations.AddField(
            model_name='registrationmandate',
            name='is_seal_authorized',
            field=models.BooleanField(default=False, verbose_name='用印授權'),
        ),
    ]
