# Generated by Django 5.1.5 on 2026-01-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_registrationmandate_is_drafting_agreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmandate',
            name='delivery_method',
            field=models.CharField(choices=[('self', '親自領取'), ('post', '郵寄送達'), ('courier', '快遞')], default='self', max_length=20, verbose_name='交付方式'),
        ),
    ]
