# Generated by Django 5.1.5 on 2026-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_registrationmandate_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmandate',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='registrationmandate',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('self', '親自領取'), ('post', '郵寄送達')], max_length=20, null=True, verbose_name='交付方式'),
        ),
    ]
