# Generated by Django 5.1.5 on 2026-01-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_registrationmandate_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmandate',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('self', '自取'), ('post', '郵寄')], max_length=20, null=True, verbose_name='交付方式'),
        ),
        migrations.AlterField(
            model_name='registrationmandate',
            name='is_drafting_agreed',
            field=models.BooleanField(default=True, verbose_name='擬稿同意'),
        ),
        migrations.AlterField(
            model_name='registrationmandate',
            name='is_seal_authorized',
            field=models.BooleanField(default=True, verbose_name='用印授權'),
        ),
    ]
